alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 5s
  external_labels:
    monitor: docker-host-alpha
  scrape_interval: 5s
remote_write:
- queue_config:
    max_samples_per_send: 1000
    max_shards: 1000
  url: http://35.242.227.62:9201/write
rule_files:
- alert.rules
scrape_configs:
- job_name: nodeexporter
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter:9100
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- honor_labels: true
  job_name: pushgateway
  scrape_interval: 5s
  static_configs:
  - targets:
    - pushgateway:9091
- job_name: nodeexporter1
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter1:9101
- job_name: nodeexporter2
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter2:9102
- job_name: nodeexporter3
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter3:9103
- job_name: nodeexporter4
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter4:9104
- job_name: nodeexporter5
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter5:9105
- job_name: nodeexporter6
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter6:9106
- job_name: nodeexporter7
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter7:9107
- job_name: nodeexporter8
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter8:9108
- job_name: nodeexporter9
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter9:9109
- job_name: nodeexporter10
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter10:9110
- job_name: nodeexporter11
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter11:9111
- job_name: nodeexporter12
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter12:9112
- job_name: nodeexporter13
  scrape_interval: 5s
  static_configs:
  - targets:
    - nodeexporter13:9113
